### last 요청 ㅇ
GET http://localhost:8080/api/sensor/humidity
    /fields/value
    /branches/nhnacademy
    /places/class_a
    /sensors/24e124128c067999
    /last
Content-Type: application/json

### 5m 요청 ㅇ
GET http://localhost:8080/api/sensor/humidity
    /fields/humidity_mean
    /branches/nhnacademy
    /places/class_a
    /sensors/24e124128c067999
    /hour
    /mean?begin=2024-05-15T05:30:00Z&end=2024-05-15T06:30:00Z
Content-Type: application/json

### 1h 요청 ㅇ
GET http://localhost:8080/api/sensor/humidity
    /fields/humidity_mean
    /branches/nhnacademy
    /places/class_a
    /sensors/24e124128c067999
    /day
    /mean?begin=2024-05-14T06:30:00Z&end=2024-05-15T06:30:00Z
Content-Type: application/json

### week min 요청 ㅇ
GET http://localhost:8080/api/sensor/humidity
    /fields/humidity_min
    /branches/nhnacademy
    /places/class_a
    /sensors/24e124128c067999
    /week
    /min?begin=2024-05-08T06:30:00Z&end=2024-05-15T06:30:00Z
Content-Type: application/json

### week max 요청 ㅇ
GET http://localhost:8080/api/sensor/humidity
    /fields/humidity_max
    /branches/nhnacademy
    /places/class_a
    /sensors/24e124128c067999
    /week
    /max?begin=2024-05-08T06:30:00Z&end=2024-05-15T06:30:00Z
Content-Type: application/json

