### last 요청 ㅇ
GET http://localhost:8099/api/sensor/temperature
    /fields/value
    /branches/nhnacademy
    /places/class_a
    /sensors/24e124128c067999
    /last
Content-Type: application/json

### 5m 요청 ㅇ
GET http://localhost:8099/api/sensor/temperature
    /fields/temperature_mean
    /branches/nhnacademy
    /places/class_a
    /sensors/24e124128c067999
    /hour
    /mean?begin=2024-05-26T05:00:37.516416000Z&end=2024-05-26T06:00:37.516416000Z
Content-Type: application/json

### 1h 요청 ㅇ
GET http://localhost:8099/api/sensor/temperature
    /fields/temperature_mean
    /branches/nhnacademy
    /places/class_a
    /sensors/24e124128c067999
    /day
    /mean?begin=2024-05-25T06:00:37.516416000Z&end=2024-05-26T06:00:37.516416000Z
Content-Type: application/json

### week min 요청 ㅇ
GET http://localhost:8099/api/sensor/temperature
    /fields/temperature_min
    /branches/nhnacademy
    /places/class_a
    /sensors/24e124128c067999
    /week
    /min?begin=2024-05-18T06:00:37.516416000Z&end=2024-05-25T06:00:37.516416000Z
Content-Type: application/json

### week max 요청 ㅇ
GET http://localhost:8099/api/sensor/temperature
    /fields/temperature_max
    /branches/nhnacademy
    /places/class_a
    /sensors/24e124128c067999
    /week
    /min?begin=2024-05-18T06:00:37.516416000Z&end=2024-05-25T06:00:37.516416000Z
Content-Type: application/json

