### last 요청 ㅇ
GET http://localhost:8080/api/data/temperature
    /fields/value
    /branches/gyeongnam
    /places/class_a
    /sensors/24e124126d152969
    /last
Content-Type: application/json

### 5m 요청 ㅇ
GET http://localhost:8080/api/data/temperature
    /fields/temperature_mean
    /branches/gyeongnam
    /places/class_a
    /sensors/24e124126d152969
    /hour
    /mean?begin=2024-05-14T06:44:57Z&end=2024-05-14T07:44:28Z
Content-Type: application/json

### 1h 요청 ㅇ
GET http://localhost:8080/api/data/temperature
    /fields/temperature_mean
    /branches/gyeongnam
    /places/class_a
    /sensors/24e124126d152969
    /day
    /mean?begin=2024-05-13T07:14:57Z&end=2024-05-14T07:44:28Z
Content-Type: application/json

### week min 요청 ㅇ
GET http://localhost:8080/api/data/temperature
    /fields/temperature_min
    /branches/gyeongnam
    /places/class_a
    /sensors/24e124126d152969
    /week
    /min?begin=2024-05-07T07:14:57Z&end=2024-05-14T07:44:28Z
Content-Type: application/json

### week max 요청 ㅇ
GET http://localhost:8080/api/data/temperature
    /fields/temperature_max
    /branches/gyeongnam
    /places/class_a
    /sensors/24e124126d152969
    /week
    /max?begin=2024-05-07T07:14:57Z&end=2024-05-14T07:44:28Z
Content-Type: application/json

