### 일반 설정 등록
POST http://localhost:8080/api/sensor/generalConfig/register
Content-Type: application/json

{
  "sensorSn": "hum01",
  "functionId": 1
}


### 일반 설정 수정
POST http://localhost:8080/api/sensor/generalConfig/modify
Content-Type: application/json

{
  "configId": 5,
  "functionId": 2
}


### 일반 설정 조회
GET http://localhost:8080/api/sensor/generalConfig/4
Content-Type: application/json


### 특정 부서의 일반 설정 조회
GET http://localhost:8080/api/sensor/generalConfig?organizationName=nhnacademy1


### 일반 설정 삭제
DELETE http://localhost:8080/api/sensor/generalConfig/5




