POST http://localhost:8080/api/sensor/generalConfig/register
Content-Type: application/json

{
  "sensorSn": "temp03",
  "functionId": 1
}


###
POST http://localhost:8080/api/sensor/generalConfig/register
Content-Type: application/json

{
"sensorSn": "hum01",
"functionId": 2
}


###
POST http://localhost:8080/api/sensor/temperatureConfig/register
Content-Type: application/json

{
  "configId": 33,
  "targetValue": 21,
  "deviationValue": 3
}


###
POST http://localhost:8080/api/sensor/temperatureConfig/modify
Content-Type: application/json

{
  "configId": 33,
  "targetValue": 22,
  "deviationValue": 3
}


###
DELETE http://localhost:8080/api/sensor/temperatureConfig/delete
Content-Type: application/json

{
  "configId": 27
}

###
POST http://localhost:8080/api/sensor/humidityConfig/register
Content-Type: application/json

{
  "configId": 34,
  "targetValue": 21,
  "deviationValue": 3
}


###
POST http://localhost:8080/api/sensor/humidityConfig/modify
Content-Type: application/json

{
"configId": 34,
"targetValue": 24,
"deviationValue": 3
}


###
DELETE http://localhost:8080/api/sensor/humidityConfig/delete
Content-Type: application/json

{
"configId": 34
}