### 센서 등록
POST http://localhost:8080/api/sensor/sensor/register
Content-Type: application/json

{
  "sensorSn": "hum01",
  "organizationId": 1,
  "sensorTypeId": 2,
  "sensorName": "습도1",
  "sensorPlace": "강의실A"
}


### 센서 수정
POST http://localhost:8080/api/sensor/sensor/modify
Content-Type: application/json

{
  "sensorSn": "temp02",
  "organizationId": 1,
  "sensorTypeId": 1,
  "sensorName": "온도1",
  "sensorPlace": "강의실A"
}


### 센서 조회
GET http://localhost:8080/api/sensor/sensor/temp01


### 특정 조직의 센서 목록 조회
GET http://localhost:8080/api/sensor/sensor?organizationId=1


### 센서 삭제
DELETE http://localhost:8080/api/sensor/sensor/temp02