### 설정 기능 타입 등록
POST http://localhost:8080/api/sensor/settingFunction/register
Content-Type: application/json

{
  "functionName": "ai"
}


### 설정 기능 타입 수정
POST http://localhost:8080/api/sensor/settingFunction/modify
Content-Type: application/json

{
  "functionId": 4,
  "functionName": "ai1"
}


### 설정 기능 타입 목록 조회
GET http://localhost:8080/api/sensor/settingFunction
Content-Type: application/json


### 센서 타입 삭제
DELETE http://localhost:8080/api/sensor/settingFunction/4