### 장치 등록
POST http://localhost:8080/api/sensor/org/1/device
Content-Type: application/json

{
  "deviceSn": "air1",
  "deviceName": "에어컨1"
}


### 장치 수정
PUT http://localhost:8080/api/sensor/org/1/device/air1
Content-Type: application/json

{
  "deviceName": "에어컨"
}


### 장치 조회
GET http://localhost:8080/api/sensor/org/1/device/air1


### 특정 조직의 장치 목록 조회
GET http://localhost:8080/api/sensor/org/1/device/all


### 장치 삭제
DELETE http://localhost:8080/api/sensor/org/1/device/air1