### 일반 설정 등록
POST http://localhost:8080/api/sensor/org/1/general?sensorSn=hum03&sensorTypeId=2
Content-Type: application/json
X-USER-ID: owner

{
  "functionId": 1
}


### 일반 설정 수정
PUT http://localhost:8080/api/sensor/org/1/general?sensorSn=hum03&sensorTypeId=2
Content-Type: application/json
X-USER-ID: owner

{
  "functionId": 2,
  "deviceSn": "air1"
}


### 일반 설정 조회
GET http://localhost:8080/api/sensor/org/1/general?sensorSn=hum03&sensorTypeId=2
Content-Type: application/json
X-USER-ID: owner


### 특정 부서의 일반 설정 조회
GET http://localhost:8080/api/sensor/org/1/general/all
Content-Type: application/json
X-USER-ID: owner


### 일반 설정 삭제
DELETE http://localhost:8080/api/sensor/org/1/general?sensorSn=hum03&sensorTypeId=2
Content-Type: application/json
X-USER-ID: owner



