### 사용자 설정 등록
POST http://localhost:8080/api/sensor/org/1/value?sensorSn=hum02&sensorTypeId=2
Content-Type: application/json
X-USER-ID: owner

{
  "firstEntry": "18",
  "secondEntry": "3"
}


### 사용자 설정 수정
PUT http://localhost:8080/api/sensor/org/1/value/8?sensorSn=hum03&sensorTypeId=2
Content-Type: application/json
X-USER-ID: owner

{
  "firstEntry": "18",
  "secondEntry": "4"
}


### 사용자 설정 조회
GET http://localhost:8080/api/sensor/org/1/value/8?sensorSn=hum03&sensorTypeId=2
Content-Type: application/json
X-USER-ID: owner


### 특정 부서의 사용자 설정 조회
GET http://localhost:8080/api/sensor/org/1/value
Content-Type: application/json
X-USER-ID: owner


### 사용자 설정 삭제
DELETE http://localhost:8080/api/sensor/org/1/value/9?sensorSn=hum02&sensorTypeId=2
Content-Type: application/json
X-USER-ID: owner

