### 사용자 설정 등록
POST http://localhost:8080/api/sensor/org/1/sensor/hum02/type/2/value
Content-Type: application/json

{
  "firstEntry": "18",
  "secondEntry": "3"
}


### 사용자 설정 수정
PUT http://localhost:8080/api/sensor/org/1/sensor/hum02/type/2/value/1
Content-Type: application/json

{
  "firstEntry": "18",
  "secondEntry": "4"
}


### 사용자 설정 조회
GET http://localhost:8080/api/sensor/org/1/sensor/hum02/type/2/value/1
Content-Type: application/json


### 특정 부서의 사용자 설정 조회
GET http://localhost:8080/api/sensor/org/1/sensor/all/type/2/value


### 사용자 설정 삭제
DELETE http://localhost:8080/api/sensor/org/1/sensor/hum02/type/2/value/1

